# Generated by Django 3.1 on 2020-08-27 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('akronim', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kkm', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('10', 'X'), ('11', 'XI'), ('12', 'XII')], max_length=3)),
                ('kelas', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('nama', models.CharField(blank=True, max_length=15, null=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='Kelas.jurusan')),
                ('matapelajaran', models.ManyToManyField(related_name='kelas', to='Kelas.MataPelajaran')),
            ],
        ),
    ]
