# Generated by Django 3.1 on 2020-08-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kelas', '0002_kelas_walikelas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MataPelajaran',
        ),
    ]
