# Generated by Django 3.1 on 2020-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kelas', '0004_auto_20200829_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='nama',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
