# Generated by Django 3.1 on 2020-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kelas', '0005_auto_20200831_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='nama',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
