# Generated by Django 3.1 on 2020-09-01 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20200901_1144'),
        ('Kelas', '0006_auto_20200901_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='walikelas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas', to='User.guru'),
        ),
    ]
