# Generated by Django 3.1 on 2020-09-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nilai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matapelajaran',
            name='jenis',
            field=models.CharField(choices=[('NA', 'Normatif Adaptif'), ('Produktif', 'Produktif'), ('Mulok', 'Muatan Lokal')], default='NA', max_length=15),
        ),
    ]
