# Generated by Django 3.1 on 2020-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200827_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='nis',
            field=models.CharField(default='null', editable=False, max_length=9, unique=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(default='null', max_length=10, unique=True),
        ),
    ]
