# Generated by Django 3.1 on 2020-08-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20200831_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
