# Generated by Django 3.1 on 2020-09-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20200901_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(editable=False, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
