# Generated by Django 3.1 on 2020-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20200901_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(editable=False, max_length=18),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nisn',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
