# Generated by Django 3.1 on 2020-09-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_auto_20200916_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nama',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
