# Generated by Django 3.1 on 2020-12-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_auto_20200916_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='tu',
            field=models.BooleanField(default=False),
        ),
    ]
