# Generated by Django 3.1 on 2020-12-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_auto_20201205_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nama',
        ),
    ]
