# Generated by Django 3.1 on 2020-12-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_auto_20201205_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('A', 'Admin'), ('G', 'Guru'), ('T', 'Staf TU')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
