# Generated by Django 3.1 on 2020-12-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_auto_20201213_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nama',
        ),
    ]
